export { default as LandingPage } from './LandingPage/LandingPage';
export { default as RankingPage } from './RankingPage/RankingPage';
export { default as RaceToLondonPage } from './RaceToLondon/RaceToLondonPage';
export { default as CurrentTournamentsPage } from './CurrentTournaments/CurrentTournamentsPage';
export { default as SeasonPage } from './SeasonPage/SeasonPage';
export { default as NewsPage } from './NewsPage/NewsPage';
export { default as UserPage } from './UserPage/UserPage';
export { default as SignInPage } from './SignInPage/SignInPage';
export { default as SignUpPage } from './SignUpPage/SignUpPage';